# Generated by Django 5.2.14 on 2026-06-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailconfirmationtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('buyer', 'Покупатель'), ('supplier', 'Поставщик'), ('storekeeper', 'Кладовщик')], default='buyer', max_length=20, verbose_name='Тип пользователя'),
        ),
    ]
