# Generated by Django 5.2.14 on 2026-06-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('buyer', 'Покупатель'), ('supplier', 'Поставщик'), ('storekeeper', 'Кладовщик'), ('admin', 'Администратор')], default='buyer', max_length=20, verbose_name='Тип пользователя'),
        ),
    ]
