# Generated by Django 5.2.14 on 2026-05-26 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_shop_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinfo',
            name='quantity',
        ),
    ]
