# Generated by Django 5.2.14 on 2026-05-27 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_productinfo_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество на складе'),
        ),
    ]
