# Generated by Django 5.2.14 on 2026-05-27 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_productinfo_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='yaml_file',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Путь к файлу импорта'),
        ),
    ]
