# Generated by Django 5.2.14 on 2026-06-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmed_shops',
            field=models.TextField(blank=True, default='', verbose_name='ID подтверждённых магазинов'),
        ),
    ]
